jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Install dependencies
        run: npm install
        working-directory: tauri-app
      - name: Build Windows EXE
        uses: tauri-apps/tauri-action@v0
        with:
          projectPath: "tauri-app"
      - name: Upload Windows installers
        uses: actions/upload-artifact@v4
        with:
          name: game-tool-windows
          path: |
            tauri-app/src-tauri/target/release/bundle/windows/nsis/*-setup.exe
            tauri-app/src-tauri/target/release/bundle/msi/*.msi
